### ISSUE TITLE
Command chaining operators are not allowed (;, &, |, `)

### ISSUE THREAD

**Issue by BartNetJS** [SimonB97/win-cli-mcp-server#1]
Hi, came across this issue:

{
  `shell`: `powershell`,
  `command`: `[some powershell with a query paramater]' 'AzureDiagnostics | take 2'`
}

So when passing parameters like a kudo query in this case should allow the pipe character

I know i can disable that check globally, but that's risky.

**Comment by SimonB97** [comment]
Have you tried adjusting the `enableInjectionProtection` setting in your config file? You can set this to `false` in your configuration to allow pipe operations:

```json
{
  "security": {
    "enableInjectionProtection": false
  }
}
```

Could you try this and let me know if it solves your issue?

**Comment by SimonB97** [comment]
I have added a shell-specific `blockedOperators` setting to the config in version `0.1.8`. You can pass a list of operators to be blocked (if `enableInjectionProtection` is set to `true`):

```json
{
  "security": {
    "enableInjectionProtection": true
  }
  "cmd": {
        "enabled": true,
        "command": "cmd.exe",
        "args": ["/c"],
        "blockedOperators": ["&", "|", ";", "`"]
  }
}
```

Let me know if this doesn't solve the issue, otherwise I'll consider this solved and close.

P.S.: Thanks for being my first issue! 🥇

**Comment by BartNetJS** [comment]
Hi @SimonB97, thanks for the quick fix
